18F/nsf

PULL_REQUEST_TEMPLATE.md

We were referencing nsf-sbir, Federalist, and Circle; none of which are used in this project.

Remove irrelevant references from PR template

---

bootstrap.sh
cronish.sh
manifest.yml

Cloud.gov doesn't offer time-based task execution yet; luckily, it's very easy
to imitate with a loop in bash. This'll execute the `cron:execute` command
roughly every 15m (there's a slight skew due to amount of time processing that
command).
It also moves app configuration up a level in the manifest, as most of these
configs are shared and reduces our apps' memory resources.

Add a "cronish" worker to call cron every 15m.

---

bootstrap.sh
manifest-prod.yml

This prepares us for the production environment by creating a new,
production-specific manifest file. It's a duplicate of manifest.yml, changing
only the "domains" key. Cloud Foundry's manifest inheritance is deprecated,
but they haven't implemented their variable substitution strategy yet, so this
duplication seems like the best path forward.
This renames the application to "web" so there isn't an "nsf-demo" app in the
"prod" space.
To deploy to prod, we'll run:
```
cf target -o nsf-prototyping -s prod
cf push -f manifest-prod.yml
```

Add production manifest; rename web app.

---

bootstrap.sh
web/sites/default/config/.htaccess
web/sites/default/settings.php

We can configure Drupal to import/export configs to a directory, rather than needing to spell it out when invoking `drush` or `drupal`. This also resolves a 500 error when attempting to access the configs (it now correctly returns a 403).
It might make sense to instead move the configs out of the `web` directory and into a peer `config/sync` (the default) dir. The configs contain sensitive info -- I'm a bit concerned that an htaccess file isn't enough to hide them.

Tell Drupal our config location; fix htaccess bug

---

web/sites/default/config/dblog.settings.yml

As part of our SSR, we're claiming to store logs for at least a year. We've
also noted that the logs are stored (for now) in the database.
As @fureigh pointed out, this is a frequent performance bottleneck for Drupal
sites. Unfortunately, there's not enough runway to create a longer term
solution (like writing to syslog) as we know from our users that they want to
see subsets of the logs within the application. We're kicking that can down
the road a bit.

Set logs to store indefinitely.

---

web/sites/default/config/system.site.yml

This pull request does the following:
- Changes the site name to `beta.nsf.gov`
- Changes the homepage from a placeholder blank page to the social media page

Update site name and homepage

---

README.md
docker-compose.yml
web/sites/default/config/core.extension.yml
web/sites/default/config/field.storage.node.field_featured_image.yml
web/sites/default/config/field.storage.user.user_picture.yml

We had been including the flysystem dependencies but hadn't configured its
use. This sets our two image fields to store their content in s3 (as the local
file system is volatile and may disappear between app restarts).
It also updates the README and docker-compose file so everything continues to _run_ locally (though see the note in the README around actually uploading files).

Enable S3 storage for our image fields.

---

web/sites/default/config/block.block.nsf_account_menu.yml

No one's meant to log in, currently, so let's not present the link.
https://github.com/18F/nsf/issues/161
https://github.com/18F/nsf/issues/162
Changes proposed in this pull request:
* Remove the `account menu` block from the header.
Technical notes:
* Here I've disabled the block, not removed it. This was for ease of re-adding it in the future, but another option is to entirely remove it; a future developer would still be able to restore it by reverting the commit(s) from this PR.
* In a separate issue, let's programmatically prevent people from being able to log in. (Remove the `/user/login` route, etc.)

Remove account menu, including 'log in' link

---

web/sites/default/config/nsf.settings.yml

This pull request adds a banner that reads "An official website of the United States government. Here's how you know", with a link to more information.
Related issues:
* Part of https://github.com/18F/nsf/issues/162.
* A step toward https://github.com/18F/nsf/issues/193. Next step: update the content to be beta-specific.
Changes proposed in this pull request:
* Add the standard "An official website of the United States government" banner

Add standard government banner from USWDS

---

manifest-prod.yml

Per conversation with Matt and Theresa, we don't want beta to be associated
with NSF until there's a full time team.

Unbind beta.nsf.gov.

---

bootstrap.sh
web/sites/default/config/core.extension.yml

Per the experience we had when uninstalling workflow, we know we need to run
the `module:uninstall` command and _keep_ the PHP code until the modules are
completely removed from all environments. This is the first step of that
process.
This manifests the changes I recommended in #195

Uninstall masquerade.

---

cronish.sh

Unfortunately, `cron:execute` claims everything went well, but doesn't
actually execute any cron tasks. By adding the "all" parameter, we solve his
problem.
Fixes issue(s) #203 .

Execute all cron tasks every 15m.

---

README.md
bootstrap.sh
composer.json
composer.lock
web/sites/default/config/core.extension.yml
web/sites/default/config/hal.settings.yml
web/sites/default/config/serialization.settings.yml
web/sites/default/content/.htaccess
web/sites/default/content/aggregator_feed/3f9d422e-3eb3-406c-b3e3-c4618832738e.json
web/sites/default/content/aggregator_feed/c79e1596-ba1f-48be-b953-94815ad66d7e.json
web/sites/default/settings.php

Building off the Drush PR (#209), this adds the [Default Content Deploy](https://www.drupal.org/project/default_content_deploy) module and commits our initial aggregator feeds to code.

Add mechanism for initial content

---

.docker/Dockerfile
README.md
bootstrap.sh
composer.json
composer.lock
manifest.yml
multi-buildpack.yml
web/sites/default/config/core.extension.yml
web/sites/default/config/hal.settings.yml
web/sites/default/config/serialization.settings.yml
web/sites/default/content/.htaccess
web/sites/default/content/aggregator_feed/3f9d422e-3eb3-406c-b3e3-c4618832738e.json
web/sites/default/content/aggregator_feed/c79e1596-ba1f-48be-b953-94815ad66d7e.json
web/sites/default/settings.php

Drush requires a mysql command line client. While I'd argue that that's a big design flaw (and a strong argument to use drupal console where possible), much of Drupal-land still builds towards Drush. This adds mysql to both the Docker image and cloud.gov environment.
Fixes issue(s) #179  .

Allow Drush to be ran locally and in cloud.gov

---

web/sites/default/config/user.role.anonymous.yml

Per #205, we don't want anonymous users to be able to submit to the contact
from. We *may* want internal users to have access, in the future, however.
Fixes #205

Remove contact form permission from anon users.

---

web/sites/default/config/views.view.nsf_blog.yml

Cleaning up the appearance of the aggregated Tumblr posts.
Prompted by working on issue #220.

Remove `more` link and pager

---

composer.lock

There was a security vulnerability around the WYSIWYG editor. We tested
locally.

Update to Drupal 8.5.2.

---

web/sites/default/config/aggregator.settings.yml

Tumblr's RSS feeds use iframes for presenting YouTube videos, so this pull request adds them to the list of allowed tags.
(Please note that this change doesn't modify feed items that have already been imported. To have this change affect already-posted feed items, the items must be deleted and re-'updated'. Fortunately, our deployment process has the same effect.)
Fixes issue #219.

Include videos in imported Tumblr posts

---

composer.json

#225 updated Drupal to the most recent version, following the announcement of a security vulnerability. This PR simply updates composer.json to indicate more clearly (to the human eye)
that we're running Drupal 8.5.* or better.

Update composer.json to indicate Drupal 8.5+

---

multi-buildpack.yml

Fixes issue(s) # 234.
Changes proposed in this pull request:
- Update multi-buildpack.yml to change php-buildpack version to 4.3.53
This has not been tested locally yet.

Updated php-buildpack to v4.3.53 per issue 234

---

composer.lock
web/.ht.router.php
web/robots.txt

Drupal core issued a security release today that bumps up their dependent
libraries: https://www.drupal.org/SA-CORE-2018-005
To satisfy, this updates Drupal and three of the symfony libraries it depends
on. In one of the patch releases sine 8.5.3, Drupal also modified two of the
files it auto-creates; we've included those changes here as well.

Bump to Drupal 8.5.6.
